CREATE TABLE PRODUCTS (
    PRODUCT_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DS_PRODUCT VARCHAR(255) NOT NULL,
    PRICE DECIMAL(12,4),
    CATEGORY VARCHAR(40),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE SEQUENCE PRODUCT_ID_SEQ;